### ISSUE TITLE
Add 2 columns in User List showing "Access Type"

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#50] opened 2017-08-21 10:05 UTC
@benjaminl83 @purnomoeko Add 2 columns in User List showing "Access Type"

https://raimon-land-sales-matrix.firebaseapp.com/user

<img width="701" alt="capture" src="https://user-images.githubusercontent.com/30112738/29514478-f3550ea6-8692-11e7-8bea-fffb383bf519.PNG">

**Comment by benjaminl83** [comment] 2017-08-22 16:18
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by chuanhiang** [comment] 2017-08-29 14:01
@fransjosua 

This is not fixed.

Thanks.

**Comment by benjaminl83** [comment] 2017-08-30 02:31
Confirmed
![image](https://user-images.githubusercontent.com/18274902/29852741-50bdcdb2-8d6e-11e7-9638-820b6cdbc098.png)

**Comment by Ponpimonk** [comment] 2017-08-30 03:43
OK

**Closed** 2017-08-30 03:43 UTC
Labels: enhancement, Need Testing
